language: zh

pipeline:
  # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
  # # If you'd like to customize it, uncomment and adjust the pipeline.
  # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: components.bert_tokenizer.CustomBertTokenizer
    model_name: bert
    model_weights: bert-base-chinese
    cache_dir: ./models/pre-train/
  - name: LanguageModelFeaturizer
    model_name: bert
    model_weights: bert-base-chinese
    cache_dir: ./models/pre-train/
  - name: DIETClassifier
    epochs: 150
    constrain_similarities: True
    model_confidence: linear_norm
  - name: RegexEntityExtractor
    case_sensitive: False
    use_lookup_tables: True
    use_regexes: True
    use_word_boundaries: False
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    embedding_dimension: 100
    retrieval_intent: chat
  - name: FallbackClassifier
    threshold: 0.2
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
  - name: RulePolicy